FROM golang:latest
# Create and change to the app directory.
WORKDIR /app

# Retrieve application dependencies.
# This allows the container build to reuse cached dependencies.
# Expecting to copy go.mod and if present go.sum.
COPY go.* ./
RUN go mod download

# Copy local code to the container image.
COPY . ./

# Run the web service on container startup.

# This container exposes port 7000 to the outside world.
EXPOSE 7000

# Build the binary.
RUN go build -v -o cache_server

# Run the web service on container startup.
CMD ["./cache_server"]
