name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Go project
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22' # Buradaki sürümü projenizde kullandığınız Go sürümüne göre ayarlayın

    - name: Build
      run: go build -o app

    - name: Archive build
      uses: actions/upload-artifact@v2
      with:
        name: CustomCache
        path: ./CustomCache

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Download build
      uses: actions/download-artifact@v2
      with:
        name: CustomCache
        path: ./CustomCache

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body: |
          Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./CustomCache/CustomCache
        asset_name: CustomCache
        asset_content_type: application/octet-stream
